In [84]:
import pandas as pd
import numpy as np

In [85]:
df = pd.read_csv('placement-dataset.csv')

In [86]:
df

city  cgpa     iq  placement
0      New York   6.8  123.0          1
1   Los Angeles   5.9  106.0          0
2       Chicago   NaN  121.0          0
3      New York   7.4  132.0          1
4   Los Angeles   5.8  142.0          0
..          ...   ...    ...        ...
95      Chicago   4.3  200.0          0
96     New York   4.4   42.0          0
97  Los Angeles   6.7  182.0          1
98      Chicago   6.3  103.0          1
99     New York   6.2  113.0          1

[100 rows x 4 columns]

In [87]:
X = df[['iq']]
Y = df[['cgpa']]

In [88]:
from sklearn.impute import SimpleImputer

In [89]:
si = SimpleImputer()

In [90]:
X = si.fit_transform(X)
Y = si.fit_transform(Y)

In [91]:
from sklearn.model_selection import train_test_split

In [92]:
X_train , X_test , y_train , y_test = train_test_split(X  , Y , test_size = 0.2)

In [93]:
y_train.shape

(80, 1)

In [94]:
X_train

array([[141.        ],
       [114.        ],
       [200.        ],
       [120.        ],
       [146.        ],
       [116.        ],
       [120.        ],
       [151.        ],
       [168.        ],
       [ 42.        ],
       [117.91666667],
       [ 45.        ],
       [  1.        ],
       [135.        ],
       [121.        ],
       [134.        ],
       [154.        ],
       [128.        ],
       [116.        ],
       [112.        ],
       [182.        ],
       [121.        ],
       [137.        ],
       [176.        ],
       [ 64.        ],
       [128.        ],
       [ 66.        ],
       [123.        ],
       [ 91.        ],
       [ 86.        ],
       [132.        ],
       [ 37.        ],
       [156.        ],
       [158.        ],
       [183.        ],
       [113.        ],
       [ 96.        ],
       [160.        ],
       [ 89.        ],
       [138.        ],
       [142.        ],
       [106.        ],
       [124.        ],
       [107

# Now we will calculate the class

In [95]:
class SimpleAlgo:
    def __init__(self):
        self.m = None
        self.b = None

    def fit(self , X_train , y_train):
        num = 0
        den = 0

        for i in range(X_train.shape[0]):
            num = num + (X_train[i] - X_train.mean())*(y_train[i] - y_train.mean())
            den = den + (X_train[i] - X_train.mean())*(X_train[i] - X_train.mean())
        self.m = num / den
        self.b = y_train.mean() - (self.m * X_train.mean())
        print(self.m)
        print(self.b)

    def predict(self , X_test):
        return self.m * X_test + self.b
    

In [96]:
lr = SimpleAlgo()

In [97]:
lr.fit(X_train , y_train)

[-0.00122401]
[6.13345637]


In [99]:
lr.predict(X_test[0])

array([6.05879167])

# Now using Sklearn and we compare

In [100]:
gf = pd.read_csv('placement-dataset.csv')

In [101]:
X2 = gf[['iq']]
Y2 = gf[['cgpa']]

In [102]:
si = SimpleImputer()

In [103]:
X_train2 , X_test2 , y_train2 , y_test2 = train_test_split(X2 , Y2 , test_size = 0.2)

In [104]:
X_train2 = si.fit_transform(X_train2)
X_test2 = si.transform(X_test2)

y_train2 = si.fit_transform(y_train2)
y_test2 = si.fit_transform(y_test2)

In [106]:
from sklearn.linear_model import LinearRegression

In [107]:
lra = LinearRegression() 

In [108]:
lra.fit(X_train , y_train)

LinearRegression()

In [113]:
lra.predict(X_test)[0]

array([6.05879167])